services:
  - type: web
    name: myapp
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn Config.wsgi:application
